layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

title: Formation Android

videos:
  - title: Intro
    id: C2-2Wg800vs
  - title: Views
    id: x_hgFEmtQR4
  - title: RecyclerView
    id: h-jCxZMjgnE
  - title: Jetpack Compose
    id: SrnmTIhiZ8Y
  - title: Intents
    id: UPZ-LmDoGcY