layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

title: Formation Android

videos:
  - title: Intro
    url: https://www.youtube.com/embed/C2-2Wg800vs
  - title: Views
    url: https://www.youtube.com/embed/x_hgFEmtQR4
  - title: RecyclerView
    url: https://youtu.be/h-jCxZMjgnE
  - title: Jetpack Compose
    url: https://youtu.be/SrnmTIhiZ8Y