# This is a basic workflow to help you get started with Actions

name: Build Codelabs

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tp/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17.1'
      - name: Install claat
        # run: go get github.com/googlecodelabs/tools/claat
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Pre Process
        run: python3 ./scripts/pre_codelabs.py
      - name: Build codelabs
        run: claat export -o codelabs/ tp/TP*.md
      - name: Post Process
        run: python3 ./scripts/post_codelabs.py
      - name: Push
        run: |
          git config user.name "Codelabs Builder"
          git config user.email "<>"
          git add codelabs/*
          git commit -m "build codelabs"
          git push
