name: Build Codelabs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tp/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Pre Process
        run: python3 ./scripts/pre_codelabs.py
      - name: Clean previous
        run: rm -rf codelabs/TP*
      - name: Build codelabs
        run: claat export -o codelabs/ tp/TP*.md
      - name: Post Process
        run: python3 ./scripts/post_codelabs.py
      - name: Push
        run: |
          git pull
          git config user.name "Codelabs Builder"
          git config user.email "<>"
          git add codelabs/*
          git commit -m "build codelabs"
          git push
