name: Build Slides

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "src/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean previous
        run: git rm slides/*.html
      - name: Marp Build (README.pdf)
        run: npx @marp-team/marp-cli@latest --input-dir src/ --output slides/
        env:
          MARP_USER: root:root
      - name: Push
        run: |
          git pull
          git config user.name "Slides Builder"
          git config user.email "<>"
          git add slides/*
          git commit -m "build slides"
          git push
  